#!/usr/bin/env python3
"""
Analyzes Maven project dependencies and outputs the dependency tree.
Performs topological sort to determine which projects must be built first.

Only includes projects that inherit from celements base-pom (directly or transitively).

Usage: ./build-dependency-tree.py [workspace_dir] [--verbose]

Options:
  --verbose, -v  Show dependency details

Generated by Claude Opus 4.5, December 2025
"""
import os
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict

# The root parent POM that all included projects must inherit from
BASE_POM_KEY = 'com.celements:base-pom'

def parse_pom(pom_path):
    """Parse a pom.xml and extract project coordinates, parent, and dependencies."""
    try:
        tree = ET.parse(pom_path)
        root = tree.getroot()
        # Handle namespace
        ns = {'m': 'http://maven.apache.org/POM/4.0.0'}
        def find_text(xpath_no_ns, xpath_ns):
            # Try without namespace first, then with
            elem = root.find(xpath_no_ns)
            if elem is None:
                elem = root.find(xpath_ns, ns)
            return elem.text if elem is not None else None
        # Get project coordinates
        group_id = find_text('groupId', 'm:groupId')
        if not group_id:
            group_id = find_text('parent/groupId', 'm:parent/m:groupId')
        artifact_id = find_text('artifactId', 'm:artifactId')
        if not artifact_id:
            return None, None, []
        project_key = f"{group_id}:{artifact_id}"
        # Get parent (tracked separately for filtering)
        parent_key = None
        parent_group = find_text('parent/groupId', 'm:parent/m:groupId')
        parent_artifact = find_text('parent/artifactId', 'm:parent/m:artifactId')
        if parent_group and parent_artifact:
            parent_key = f"{parent_group}:{parent_artifact}"
        # Get all dependencies (including parent as dependency for build order)
        dependencies = []
        if parent_key:
            dependencies.append(parent_key)
        for dep_path in ['dependencies/dependency', 'dependencyManagement/dependencies/dependency',
                         'm:dependencies/m:dependency', 'm:dependencyManagement/m:dependencies/m:dependency']:
            for dep in root.findall(dep_path, ns) if 'm:' in dep_path else root.findall(dep_path):
                dep_group = None
                dep_artifact = None
                for child in dep:
                    tag = child.tag.replace('{http://maven.apache.org/POM/4.0.0}', '')
                    if tag == 'groupId':
                        dep_group = child.text
                    elif tag == 'artifactId':
                        dep_artifact = child.text
                if dep_group and dep_artifact:
                    dependencies.append(f"{dep_group}:{dep_artifact}")
        return project_key, parent_key, list(set(dependencies))
    except Exception as e:
        print(f"Warning: Could not parse {pom_path}: {e}", file=sys.stderr)
        return None, None, []

def has_base_pom_ancestor(project_key, parents, base_pom_key, cache=None):
    """Check if project inherits from base-pom (directly or transitively)."""
    if cache is None:
        cache = {}
    if project_key in cache:
        return cache[project_key]
    if project_key == base_pom_key:
        cache[project_key] = True
        return True
    parent = parents.get(project_key)
    if not parent:
        cache[project_key] = False
        return False
    result = has_base_pom_ancestor(parent, parents, base_pom_key, cache)
    cache[project_key] = result
    return result

def find_pom_files(workspace):
    """Find all pom.xml files in the workspace."""
    poms = []
    for root, dirs, files in os.walk(workspace):
        # Skip target directories
        skip_dirs = {'target', 'bin'}
        dirs[:] = [d for d in dirs if d not in skip_dirs]
        if 'pom.xml' in files:
            poms.append(os.path.join(root, 'pom.xml'))
    return poms

def topological_sort(projects, dependencies):
    """
    Perform topological sort using Kahn's algorithm.
    Returns list of project keys in build order.
    """
    # Build adjacency list and in-degree count
    in_degree = defaultdict(int)
    graph = defaultdict(list)
    # Initialize all projects
    for project in projects:
        in_degree[project] = 0
    # Add edges (dependency -> dependent)
    for project, deps in dependencies.items():
        for dep in deps:
            if dep in projects:  # Only count internal dependencies
                graph[dep].append(project)
                in_degree[project] += 1
    # Start with nodes that have no dependencies
    queue = [p for p in projects if in_degree[p] == 0]
    result = []
    while queue:
        # Sort for deterministic output
        queue.sort()
        node = queue.pop(0)
        result.append(node)
        for neighbor in graph[node]:
            in_degree[neighbor] -= 1
            if in_degree[neighbor] == 0:
                queue.append(neighbor)
    # Check for cycles
    if len(result) != len(projects):
        remaining = set(projects) - set(result)
        print(f"Warning: Circular dependencies detected involving: {remaining}", file=sys.stderr)
        # Add remaining projects at the end
        result.extend(sorted(remaining))
    return result

def main():
    workspace = sys.argv[1] if len(sys.argv) > 1 else '.'
    verbose = '--verbose' in sys.argv or '-v' in sys.argv
    print(f"Scanning for pom.xml files in {workspace} ...", file=sys.stderr)
    
    # Find all pom files
    pom_files = find_pom_files(workspace)
    print(f"Found {len(pom_files)} pom.xml files", file=sys.stderr)
    
    # Parse all poms
    all_projects = {}  # key -> directory
    parents = {}  # key -> parent key
    dependencies = {}  # key -> [dependency keys]
    for pom_path in pom_files:
        project_key, parent_key, deps = parse_pom(pom_path)
        if project_key:
            directory = os.path.dirname(pom_path)
            all_projects[project_key] = directory
            if parent_key:
                parents[project_key] = parent_key
            dependencies[project_key] = deps
    print(f"Parsed {len(all_projects)} projects", file=sys.stderr)
    
    # Filter to only projects inheriting from base-pom
    cache = {}
    projects = {
        k: v for k, v in all_projects.items()
        if has_base_pom_ancestor(k, parents, BASE_POM_KEY, cache)
    }
    excluded = len(all_projects) - len(projects)
    print(f"Filtered to {len(projects)} projects (excluded {excluded} without {BASE_POM_KEY} ancestor)", file=sys.stderr)
    
    # Filter dependencies to only include filtered projects
    filtered_deps = {
        k: [d for d in deps if d in projects]
        for k, deps in dependencies.items()
        if k in projects
    }
    # Perform topological sort
    dependency_tree = topological_sort(set(projects.keys()), filtered_deps)
    print("\n=== DEPENDENCY TREE (top down) ===\n", file=sys.stderr)
    # Output the dependency tree
    for i, project_key in enumerate(dependency_tree, 1):
        directory = projects.get(project_key, "EXTERNAL")
        rel_dir = os.path.relpath(directory, workspace) if directory != "EXTERNAL" else "EXTERNAL"
        print(f"{rel_dir}")
    if verbose:
        print("\n=== DEPENDENCY DETAILS ===\n", file=sys.stderr)
        for project_key in dependency_tree:
            deps = filtered_deps.get(project_key, [])
            if deps:
                print(f"{project_key}:", file=sys.stderr)
                for dep in sorted(deps):
                    print(f"  <- {dep}", file=sys.stderr)

if __name__ == '__main__':
    main()
